GET http://localhost:4000/orders/fetch/ADAUSDT/1704674911138 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxYWQ4ODMyODk2MTc0ZjQyZDg0ZTlmYTM5ZTQ4N2QwN2ZlYTQwYjQ5MGM2ZjJmYjQ4NTMzMmI4MjU0NTQyODEiLCJpYXQiOjE3MDUwODE5OTUsImV4cCI6MTcwNTE2ODM5NX0.mAg9N268L7dtWP5NpiBB548uE7-PvgzVgTNeg02ceDw
content-type: application/json

GET http://localhost:4000/orders/XRPUSDT HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxYWQ4ODMyODk2MTc0ZjQyZDg0ZTlmYTM5ZTQ4N2QwN2ZlYTQwYjQ5MGM2ZjJmYjQ4NTMzMmI4MjU0NTQyODEiLCJpYXQiOjE3MDUwODE5OTUsImV4cCI6MTcwNTE2ODM5NX0.mAg9N268L7dtWP5NpiBB548uE7-PvgzVgTNeg02ceDw
content-type: application/json


GET https://api.binance.com/api/v3/exchangeInfo HTTP/1.1