GET http://localhost:4000/portfolio HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxYWQ4ODMyODk2MTc0ZjQyZDg0ZTlmYTM5ZTQ4N2QwN2ZlYTQwYjQ5MGM2ZjJmYjQ4NTMzMmI4MjU0NTQyODEiLCJpYXQiOjE3MTgzOTI2MzksImV4cCI6MTcxODQ3OTAzOX0.cBeZqUcXyxZFsAdo73y8mBI3-I-wRi8_V-wmTjLVjQI
content-type: application/json
